name: BundleMon

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Run BundleMon
        uses: bundlemon/bundlemon-action@v1
        with:
          project-id: ${{ secrets.BUNDLEMON_PROJECT_ID }}
          token: ${{ secrets.BUNDLEMON_PROJECT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}