name: Monitor Bundle Size with BundleMon

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  monitor_bundle_size:
    name: Monitor Bundle Size
    runs-on: ubuntu-latest

    env:
      BUNDLEMON_PROJECT_ID: ${{ secrets.BUNDLEMON_PROJECT_ID }}
      BUNDLEMON_PROJECT_APIKEY: ${{ secrets.BUNDLEMON_PROJECT_APIKEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build

      - name: Run BundleMon Analysis
        run: yarn bundlemon
        env:
          BUNDLEMON_PROJECT_ID: ${{ secrets.BUNDLEMON_PROJECT_ID }}
          BUNDLEMON_PROJECT_APIKEY: ${{ secrets.BUNDLEMON_PROJECT_APIKEY }}

      - name: Deploy (if on main)
        if: github.ref == 'refs/heads/main'
        run: echo "Deploying application..."

      - name: Comment on PR with BundleMon Report
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Adding PR comment with BundleMon report"
          # You can enhance this step to parse and format a BundleMon report into a GitHub PR comment.
          echo "**BundleMon Results:** See GitHub status for detailed bundle size information."
